### ISSUE TITLE
unable to connect to ghcr.io to set up HA on Raspberry Pi-5 (64 bit)

### ISSUE THREAD

**Issue by rajatarora28** [home-assistant/landingpage#130]
I am try to install Home assistant on Raspberry Pi-5 (64-bit). I keep getting 404 and 500 errors. My DNS Setting are 1.1.1.1 (primary) and 8.8.8.8 (secondary). Kindly assist here. The logs have been attached for your reference.

[HA-setup error log](https://github.com/user-attachments/files/17702182/HA-setup.error.log)

**Comment by ALIP-0** [comment]
same

**Comment by tasomaniac** [comment]
Good to know I'm not alone. I'm also trying since couple of hours. First getting 404 Client Error and then 500 toomanyrequest

**Comment by tasomaniac** [comment]
hey, I was suspecting that this is a DNS error although on my computer (on the same network), I can access github just fine. 

This recent feature (https://github.com/home-assistant/landingpage/pull/128) helped me. I disconnected my router fully (while keeping the network on). When the internet is gone, home assistant landing page asked me if I want to update my DNS. I selected Google and then restart again. Then it worked fine. 

<img width="613" alt="Screenshot 2024-11-11 at 14 57 08" src="https://github.com/user-attachments/assets/a84881b3-f200-4d34-969c-a4ab51b206f7">

@agners do you know why initially this UI did not show up? I think it should show up when we get 404 errors especially. Or alternative could be to have an advanced page where we can enable these (perhaps also other features) regardless of automatic DNS error detection.

**Comment by agners** [comment]
The reason for all these issues were an overload of the GitHub container registry (GHCR). This was a limited incident last Monday on the infrastructure side (see https://github.com/home-assistant/supervisor/issues/5405#issuecomment-2468565190 for more details).
